name: MultiLucky
main: it.multicoredev.multilucky.MultiLucky
version: 1.0.2
api-version: 1.16
author: DanTTV
softdepend: [MCCore]

commands:
  multilucky:
    aliases: [ml, mlucky]
    description: MultiLucky